### ISSUE TITLE
A note within a "Mark Correct" selection is rendered as a space on the front end.

### ISSUE THREAD

**Issue by blishen** [guardian/scribe-plugin-noting#143] opened 2016-01-11 12:25 UTC
#### Steps to reproduce:

1. In Composer write a sentence and note one word within it.
2. Select the entire sentence and mark the selection correct using the "Mark correct function".
3. Preview the article

#### Actual Result

A space is rendered on the front end where the note is positioned.

#### Desired Result

There should be no indication on the front end that a note is present at all.

#### Supporting Media

Scribe within Composer
![image](https://cloud.githubusercontent.com/assets/479167/12233323/44709134-b85e-11e5-9e3e-23668e063d3d.png)

What's rendered in "Viewer"
![image](https://cloud.githubusercontent.com/assets/479167/12233337/5ab10ea6-b85e-11e5-9659-ed3a55a5b847.png)

**Comment by alastairjardine** [comment] 2016-01-11 12:35
There's also a visual/styling thing going on here too – it's too low
contrast.

--
Alastair Jardine, Senior UX Architect

On 11 January 2016 at 12:25, David Blishen <notifications@github.com> wrote:

> Steps to reproduce:
>
>    1. In Composer write a sentence and note one word within it.
>    2. Select the entire sentence and mark the selection correct using the
>    "Mark correct function".
>    3. Preview the article
>
> Actual Result
>
> A space is rendered on the front end where the note is positioned.
> Desired Result
>
> There should be no indication on the front end that a note is present at
> all.
> Supporting Media
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/479167/12233323/44709134-b85e-11e5-9e3e-23668e063d3d.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/479167/12233337/5ab10ea6-b85e-11e5-9659-ed3a55a5b847.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/scribe-plugin-noting/issues/143>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by thekarel** [comment] 2016-01-19 15:07
Seems like extra spaces will be added around any tag, not just `<gu-note>` once they are selected and wrapped in a `<gu-correct>`. Add bold, then `<i>` then correct to see the effect. The resulting HTML is a bit too complicated but otherwise should not add an empty space:

```
<p>
    <gu-correct>Hello</gu-correct>
    <em>
        <gu-correct>o</gu-correct>
        <strong>
            <gu-correct>oo</gu-correct>
        </strong>
        <gu-correct>o</gu-correct>
    </em>
    <gu-correct>o</gu-correct>
</p>
```

![143-correct](https://cloud.githubusercontent.com/assets/2061333/12422240/cedfc776-bebd-11e5-845c-c6c9f3d0803b.gif)

**Comment by thekarel** [comment] 2016-01-26 13:23
Article to demonstrate the bug: https://composer.code.dev-gutools.co.uk/content/568a6bb2e4b081f1f0acfd0d#

HTML from Composer/api: https://composer.code.dev-gutools.co.uk/api/content/568a6bb2e4b081f1f0acfd0d?includePreview=true

HTML from CAPI (with added spaces): https://zerobin.gutools.co.uk/?187899f222092e1b#A2pyb0pvuj9K40IwNZeWtOAfq+Qe0zAHmCbbY4nwwyw=

**Comment by thekarel** [comment] 2016-01-28 11:20
Closing as the issue is not caused by the plugin. Raised it to the relevant team.

**Closed by thekarel** 2016-01-28 11:20 UTC
Labels: bug, invalid

**Comment by thekarel** [comment] 2016-02-02 10:26
Fixed in https://github.com/guardian/flexible-content/pull/2313
